const styles = {
  StartingStyle: {
    backgroundColor: "Red",
    padding: "0",
    height: "55rem",
    width: "75rem",
  },
  VATSGREYStyle: {
    position: "absolute",
    height: "128%",
    width: "100%",
    top: "0%",
    left: "0%",
  },
  DamageStyle: {
    color: "orange",
    backgroundColor: "red",
    paddingleft: "6rem",
    fontFamily: "Arial Black",
    fontSize: "40px",
    position: "absolute",
    top: "31%",
    left: "45%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  TimerStyle: {
    color: "white",
    backgroundColor: "black",
    paddingleft: "6rem",
    fontFamily: "Arial Black",
    fontSize: "60px",
    position: "absolute",
    top: "9%",
    left: "16%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  HealthStyle: {
    color: "red",
    backgroundColor: "purple",
    paddingleft: "6rem",
    fontFamily: "Arial Black",
    fontSize: "40px",
    position: "absolute",
    top: "22%",
    left: "34%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
    width: "30%",
  },
  ButtonStyle: {
    color: "white",
    backgroundColor: "lightgreen",
    paddingleft: "6rem",
    fontFamily: "Arial Black",
    fontSize: "40px",
    position: "absolute",
    top: "101%",
    left: "32.5%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  LoseStyle: {
    color: "white",
    backgroundColor: "darkred",
    paddingleft: "6rem",
    fontFamily: "Arial Black",
    fontSize: "40px",
    position: "absolute",
    top: "80%",
    left: "40.5%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  DivStyle: {
    marginleft: "20px",
  },
  VATSButtonStyle: {
    backgroundColor: "lightgreen",
    paddingleft: "6rem",
    fontFamily: "Helvetica",
    fontSize: "40px",
    position: "absolute",
    opacity: "0.65",
    color: "darkgreen",
    position: "absolute",
    top: "53%",
    left: "45%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  ButtonStyle3: {
    backgroundColor: "lightgreen",
    paddingleft: "6rem",
    fontFamily: "Helvetica",
    fontSize: "40px",
    position: "absolute",
    opacity: "0.65",
    color: "darkgreen",
    position: "absolute",
    top: "75%",
    left: "20%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  ButtonStyle4: {
    backgroundColor: "lightgreened",
    paddingleft: "6rem",
    fontFamily: "Helvetica",
    fontSize: "40px",
    position: "absolute",
    opacity: "0.65",
    color: "darkgreen",
    position: "absolute",
    top: "65%",
    left: "71%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
  ButtonStyle5: {
    backgroundColor: "lightgreen",
    paddingleft: "6rem",
    fontFamily: "Helvetica",
    fontSize: "40px",
    position: "absolute",
    opacity: "0.65",
    color: "darkgreen",
    position: "absolute",
    top: "86%",
    left: "41%",
    borderRadius: "20px",
    borderTop: "none",
    borderBottom: "none",
    borderWidth: "thick",
  },
};

export default styles;
